POST http://localhost:5000/auth/register
content-type: application/json

{
  "username": "tse23r",
  "email": "t23t@test.com",
  "password": "assw"
}


###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "login": "testuser",
  "password": "Password123"
}


###

GET http://localhost:5000/users

###

GET http://localhost:5000/users
Authorization: Bearer randomgarbage

###

GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTNiZDhhNDE5ZjlmMDQzYWQ4MTQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3ODc4NTM5MSwiZXhwIjoxNzc4Nzg2MjkxfQ.4ZMcVCh844w5mGU_m_6LozZsxr-cT1-NynSQclKNfaE


### 

POST http://localhost:5000/auth/refresh

###

POST http://localhost:5000/auth/refresh
Cookie: refreshToken=fakegarbagetoken

###

POST http://localhost:5000/auth/logout